import = ["/home/anupam/.config/alacritty/colors/Gruvbox-Dark.toml"]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold"

[font.italic]
style = "Regular"

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[scrolling]
history = 10000

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1
[window.dimensions]
columns = 80
lines = 24
