# Don't print a new line at the start of the prompt
add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$env_var\
$cmd_duration\
$jobs\
$line_break\
$custom\
$character
"""

command_timeout = 50

[line_break]
disabled = false

[cmd_duration]
min_time=2000
show_milliseconds=false

[character]
success_symbol = "[λ](bold white)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[Λ](bold green)"
# [➜](bold green)
# [←](bold red)
# [vi](bold green)

[package]
disabled = true

[git_branch]
format = '[git:\(](bold blue)[$branch](bold red)($style)[\) ](bold blue)'
