# Don't print a new line at the start of the prompt
add_newline = false

line_break = false

format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$env_var\
$custom\
$character
"""

command_timeout = 50

[character]
success_symbol = "[λ](bold white)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[Λ](bold green)"
# [➜](bold green)
# [←](bold red)
# [vi](bold green)

[package]
disabled = true

[cmd_duration]
disabled = true

[git_branch]
format = '[git:\(](bold blue)[$branch](bold red)($style)[\) ](bold blue)'
